### PR TITLE
Create import_socrata.py

### PR DESCRIPTION
**Pull request by sherryshenker**

### CODE REVIEW

**Comment by hunterowens** [comment]
@ian-r-rose can you take a look at the flake8 here? I'm getting some errors that don't make sense to me.

**Comment by ian-r-rose** [comment]
Looks like it is complaing mostly about unused imports. It should be safe
to delete them.

**Comment by ian-r-rose** [comment]
I do like the use of type annotations here. Should we add a mypy linter?

**Comment by hunterowens** [comment]
@ian-r-rose Sure! idea on how?

**Comment by ian-r-rose** [comment]
Looks like this will do the trick: https://github.com/pre-commit/mirrors-mypy#using-mypy-with-pre-commit

Unfortunately typings in the pydata ecosystem are still pretty sparse, so I don't know how many bugs this would catch, but it can't hurt.

**Comment by hunterowens** [comment]
@sherryshenker havn't had a change to look at this, but does it account for the fact that SR Numbers status changes?

**Comment by akoebs** [comment]
Merging initial run of Socrata import

**Pull request merged**
