### PR TITLE
Retire airflow

### PR DESCRIPTION
**Pull request by ian-r-rose**
This rips out all of the legacy airflow code, including the remaining dockless and transpo-related DAGs. With that removed, a lot of the civis-related deployment code can be moved to the root of the repo (docker-related, readme, etc).

We should not merge this until we are ready to actually decommission our Airflow deployment (MDS and all).

### CODE REVIEW

**Comment by hunterowens** [comment]
I think you might need to edit the `path` in the `.github/workflow`

**Comment by ian-r-rose** [comment]
Fixes #319, fixes #273, fixes #155

**Comment by hunterowens** [comment]
is it time? it's time.

**Comment by ian-r-rose** [comment]
I think so

**Pull request merged**
