### PR TITLE
Include trailers, parking in GetHelp data

### PR DESCRIPTION
**Pull request by ian-r-rose**
AKA "Ian gets to play with `reduce`"

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Okay, this is ready

**Comment by hunterowens** [comment]
Cool, let's add the `rap-shelter-updates@lacity.org` into this PR

**Comment by hunterowens** [comment]
@ian-r-rose you wanna hit the merge button on this or rerun CI?

**Comment by ian-r-rose** [comment]
I just rebased to pick up #242, so let's wait for a few minutes.

**Comment by ian-r-rose** [comment]
But let's merge on green

**Pull request merged**
