### PR TITLE
Add notebook for creating public catalog for Civis data warehouses on github pages

### LINKED ISSUE #320: Data warehouse catalog service
It would be nice to share a view into the civis data warehouse tables using a service so that external stakeholders could easily inspect it. Not the actual data, but maybe the available tables and some metadata.

### PR DESCRIPTION
**Pull request by ian-r-rose**
This creates an ipywidgets-based static HTML file out of the current list of tables in the Civis data warehouse, and uploads it to GitHub pages: https://cityoflosangeles.github.io/aqueduct/catalog.html

Nothing fancy, but perhaps useful for sharing around.

Fixes #320

### CODE REVIEW

**Comment by hunterowens** [comment]
oooh, this looks good. 

one thing I think we need to resolve is making sure the robot user can see all schemas / tables

**Comment by ian-r-rose** [comment]
Yeah, good point. We should make sure to discuss permissions issues (cf. #325) tomorrow

**Comment by hunterowens** [comment]
seems like the best way to do this is voila service it as the robot user, and make sure the robot user can read every / schema table?

**Comment by ian-r-rose** [comment]
Yeah. I wasn't fully satisfied with the user experience there due to the amount of time it took to crawl the tables. Could probably cut down the number of requests and do some async work to speed it up, though.

**Comment by hunterowens** [comment]
ah perhaps then better to schedule adn serve teh HTML as a static HTML report

**Pull request merged**
