### PR TITLE
Rap shelter layer

### PR DESCRIPTION
**Pull request by ian-r-rose**
Update to use the official shelter feature layer from SALUS. This will require downstream changes to dashboards to point at the new items.

### CODE REVIEW

**Comment by tiffanychu90** [comment]
@ian-r-rose Before merging, I have a small change on README. I'll make that commit when you're done so I can hitch a ride this PR's coattails?

**Comment by ian-r-rose** [comment]
Sure thing. Let's hold off on merging until we can talk about it in a few minutes.

**Comment by ian-r-rose** [comment]
Based on my reading of Jimmy's notes from RAP, the Echo Park Recreation Center was never active? Or at least it has been removed. We may want to filter that from the dataframe here, which could resolve the shelter count issue.

**Comment by hunterowens** [comment]
Let's merge this in the AM, but otherwise LGTM!

**Pull request merged**
